// Generated by eve. Do not edit by hand.
import { POST } from "./workflows.mjs";
import { getWorld as __eveGetWorkflowWorld } from "/Users/vishnu_mac/Desktop/room/tao.hq/bubbles.space/node_modules/.pnpm/eve@0.16.2_ai@7.0.4_zod@4.4.3__chokidar@5.0.0_dotenv@17.4.2_drizzle-orm@0.45.2_kysely@0_f8e088bf4b6703d58f84fc1822332495/node_modules/eve/dist/src/internal/workflow/runtime.js";

try {
  const __eveWorkflowWorld = await __eveGetWorkflowWorld();
  if (typeof __eveWorkflowWorld?.registerHandler === "function") {
    __eveWorkflowWorld.registerHandler("__eve627562626c65732d7370616365_wkf_workflow_", POST);
  }
} catch (err) {
  console.warn("[eve] Failed to register direct workflow queue handlers:", err);
}

export default async ({ req }) => {
  return await POST(req);
};
