// Generated by eve. Do not edit by hand.

import * as module_0 from "../../agent/agent.ts";
import * as module_1 from "../../agent/channels/eve.ts";
import * as module_2 from "../../agent/instructions/time.ts";
import * as module_3 from "../../agent/tools/canvas_add_widget.ts";
import * as module_4 from "../../agent/tools/canvas_read_widget.ts";
import * as module_5 from "../../agent/tools/canvas_remove_widget.ts";
import * as module_6 from "../../agent/tools/canvas_update_widget.ts";
import * as module_7 from "../../agent/tools/get_weather.ts";
import * as module_8 from "../../agent/tools/web_search.ts";
import * as module_9 from "../../agent/tools/wikipedia_search.ts";

export const moduleMap = Object.freeze({
  "nodes": Object.freeze({
      "__root__": Object.freeze({
              "modules": Object.freeze({
                  "agent.ts": module_0,
                  "channels/eve.ts": module_1,
                  "instructions/time.ts": module_2,
                  "tools/canvas_add_widget.ts": module_3,
                  "tools/canvas_read_widget.ts": module_4,
                  "tools/canvas_remove_widget.ts": module_5,
                  "tools/canvas_update_widget.ts": module_6,
                  "tools/get_weather.ts": module_7,
                  "tools/web_search.ts": module_8,
                  "tools/wikipedia_search.ts": module_9
                })
            })
    })
});

export default moduleMap;
